services:
  dev-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dev-container
    volumes:
      - ./:/usr/src/app:rw
    working_dir: /usr/src/app
    command: [ "tail", "-f", "/dev/null" ]
